-- StarPets: MapPersist.lua
-- Place in: ServerScriptService > Server > MapPersist (ModuleScript)
--
-- WHY THIS EXISTS
--
-- The map is generated by code every time a server starts. In edit mode the
-- Workspace is empty, so there is nothing to edit; the only way to see the map
-- is to press Play — and Studio throws away everything you change during Play
-- the moment you press Stop. Move a tree, add a building, spend an hour laying
-- out an island: it is gone on Stop, and the place file never knew about it.
--
-- That is not a bug in Studio. It is what happens when the map only exists at
-- runtime.
--
-- So the map stops being code and becomes CONTENT. You bake it into the place
-- once, and from then on it is ordinary parts you can select, drag, delete and
-- save like any other build. The game no longer rebuilds over the top of it.
--
-- The thing that made that impossible before was BEHAVIOUR. Clicking an egg
-- hatched it because a script connected MouseClick to a closure while it was
-- building that egg. Closures cannot be saved into a place file. Save the map,
-- skip the build, and every egg, shop pad and buy-gate becomes a lifeless prop.
--
-- The fix is to record the INTENT on the instance, as an attribute, and attach
-- the behaviour at runtime by reading it back:
--
--     MapPersist.Bind(clickDetector, "HatchEgg", "StarterEgg")
--
-- writes SPAction="HatchEgg", SPArg="StarterEgg" and connects the handler.
-- Attributes DO save into the place file. On a baked map, Rewire() walks the
-- workspace, finds every stamped detector and connects the same handler again.
-- One definition of what a click means, two ways of reaching it, no drift.
--
-- This is also how commercial Roblox games are built: the map is a build, the
-- code attaches behaviour by tag or attribute.

local MapPersist = {}

-- Deliberately terse: these are written onto hundreds of instances and show up
-- in the Studio properties panel, where a person may well read them.
local ACTION_ATTR = "SPAction"
local ARG_ATTR = "SPArg"

MapPersist.BAKED_ATTR = "StarPetsBaked"
MapPersist.ROOT_NAME = "StarPetsMap"

local handlers = {}
local RateLimit = nil

-- Weak keys: a detector that gets destroyed must not be kept alive by this.
local wired = setmetatable({}, { __mode = "k" })

function MapPersist.SetRateLimit(rl)
	RateLimit = rl
end

-- Register what each action name means. Called once, from the one place that
-- holds the RemoteEvents.
function MapPersist.Handlers(t)
	for k, v in pairs(t) do
		handlers[k] = v
	end
end

local warned = {}

-- ClickDetectors are NOT covered by any guard around the remotes, because no
-- remote is involved on the way in — the client clicks and Roblox fires
-- MouseClick on the server directly. An exploiter can drive that as fast as
-- they like, and one of these handlers writes to player data. Everything
-- funnels through here so a limiter can cover map interaction too.
local function fire(action, arg, player)
	local fn = handlers[action]
	if not fn then
		if not warned[action] then
			warned[action] = true
			warn(("[MapPersist] no handler for map action %q — something in the "
				.. "map is stamped with an action this build does not know about.")
				:format(tostring(action)))
		end
		return
	end
	if RateLimit and not RateLimit.Allow(player, "map:" .. action) then
		return
	end
	local ok, err = pcall(fn, player, arg)
	if not ok then
		warn(("[MapPersist] map action %q failed: %s")
			:format(tostring(action), tostring(err)))
	end
end

local function connect(inst)
	local action = inst:GetAttribute(ACTION_ATTR)
	if action == nil or wired[inst] then
		return false
	end
	local arg = inst:GetAttribute(ARG_ATTR)
	if inst:IsA("ClickDetector") then
		inst.MouseClick:Connect(function(player) fire(action, arg, player) end)
	elseif inst:IsA("ProximityPrompt") then
		inst.Triggered:Connect(function(player) fire(action, arg, player) end)
	else
		return false
	end
	wired[inst] = true
	return true
end

-- Stamp and connect in one go. Used while building, so a live-built map and a
-- baked map take exactly the same path into the handler.
function MapPersist.Bind(inst, action, arg)
	inst:SetAttribute(ACTION_ATTR, action)
	if arg ~= nil then
		inst:SetAttribute(ARG_ATTR, arg)
	end
	connect(inst)
	return inst
end

-- ============================================================
-- BAKED MAPS
-- ============================================================

function MapPersist.Root()
	return workspace:FindFirstChild(MapPersist.ROOT_NAME)
end

-- Both questions below are about the state of the world BEFORE anything built,
-- and both get asked again afterwards — by which time a generated map is
-- sitting there looking exactly like a saved one. So the answer is taken once,
-- deliberately, and remembered.
local boot = { baked = false, unflagged = false, taken = false }

function MapPersist.Boot()
	local root = MapPersist.Root()
	boot.baked = root ~= nil and root:GetAttribute(MapPersist.BAKED_ATTR) == true
	boot.unflagged = root ~= nil and not boot.baked
	boot.taken = true
	return boot.baked
end

-- A map is only treated as yours when you have said so. A place that merely
-- happens to have a StarPetsMap folder in it is the OTHER failure — somebody
-- saved after a play session and baked a stale map in by accident — and
-- silently keeping that would freeze the game on an old build forever.
function MapPersist.IsBaked()
	if not boot.taken then return MapPersist.Boot() end
	return boot.baked
end

function MapPersist.HasUnflaggedMap()
	if not boot.taken then MapPersist.Boot() end
	return boot.unflagged
end

-- Folders whose contents are created fresh every server start. If a baked place
-- saved a copy of them, the new server would spawn a second set on top and
-- every coin would be doubled up in the same spot.
MapPersist.RUNTIME_ONLY = { "CoinOrbs", "Orbs", "Pets" }

function MapPersist.ClearRuntimeLeftovers()
	local n = 0
	for _, name in ipairs(MapPersist.RUNTIME_ONLY) do
		local f = workspace:FindFirstChild(name)
		if f and f:IsA("Folder") then
			n = n + #f:GetChildren()
			f:Destroy()
		end
	end
	return n
end

-- Attach behaviour to a map that came out of the place file rather than out of
-- the builder. Returns how many things it woke up.
function MapPersist.Rewire()
	MapPersist.ClearRuntimeLeftovers()
	local n = 0
	for _, d in ipairs(workspace:GetDescendants()) do
		if connect(d) then n = n + 1 end
	end
	return n
end

-- How many stamped detectors exist versus how many are live. A baked map that
-- reports stamped > wired is one the build cannot fully drive, and that is
-- exactly the failure worth shouting about: the map looks right and does
-- nothing when you click it.
function MapPersist.Audit()
	local stamped, live, unknown = 0, 0, {}
	for _, d in ipairs(workspace:GetDescendants()) do
		local a = d:GetAttribute(ACTION_ATTR)
		if a ~= nil then
			stamped = stamped + 1
			if wired[d] then live = live + 1 end
			if handlers[a] == nil then unknown[a] = (unknown[a] or 0) + 1 end
		end
	end
	return stamped, live, unknown
end

-- ============================================================
-- THE MAP FOLDER
-- ============================================================
-- Everything the builder makes goes in here, for two reasons. Selecting one
-- folder in the Explorer and pressing Ctrl+C takes the WHOLE map — miss this
-- and a person copying "the map" gets the scenery and silently leaves every
-- buy-gate and trigger volume behind. And a map in a folder can be replaced
-- wholesale, where hundreds of loose parts in Workspace cannot be told apart
-- from anything else someone has put there.
function MapPersist.Container()
	local f = workspace:FindFirstChild(MapPersist.ROOT_NAME)
	if not f then
		f = Instance.new("Folder")
		f.Name = MapPersist.ROOT_NAME
		f.Parent = workspace
	end
	return f
end

-- ANYTHING IN HERE IS YOURS AND IS NEVER TOUCHED.
--
-- Build whatever you like in this folder in EDIT mode and the game leaves it
-- alone forever: no purge, no rebuild, no overwrite. It is the supported way to
-- add your own work on top of the generated map without baking at all.
MapPersist.CUSTOM_NAME = "MyBuild"

function MapPersist.EnsureCustomFolder()
	local f = workspace:FindFirstChild(MapPersist.CUSTOM_NAME)
	if not f then
		f = Instance.new("Folder")
		f.Name = MapPersist.CUSTOM_NAME
		f.Parent = workspace
	end
	return f
end

-- Replace a previously generated map. Only ever destroys the folder this
-- module created and the side folders the builder owns — never anything loose
-- in Workspace, and never MyBuild.
function MapPersist.ResetWorld()
	for _, n in ipairs({ MapPersist.ROOT_NAME, "AreaBarriers", "ProximityZones" }) do
		local old = workspace:FindFirstChild(n)
		if old then old:Destroy() end
	end
	return MapPersist.Container()
end

return MapPersist
