#!/usr/bin/env python3
"""A map saved into the place must still work when the builder never runs.

THE PROBLEM THIS ANSWERS

The map is generated by code at every server start. In edit mode the Workspace
is empty, so there is nothing to move, delete or add to. The only way to see the
map is to press Play — and Studio discards everything you change during Play the
instant you press Stop. Hours of building, gone, with the place file none the
wiser.

So the map becomes content: build it once, paste it into the place, save. The
game then keeps it instead of rebuilding over it.

That trade has one trap, and it is a bad one. Clicking an egg hatched it because
the builder connected MouseClick to a closure while it was making that egg.
Closures cannot be written into a place file. Save the map, skip the builder,
and every egg, gate and shop pad is a lifeless prop — a map that looks perfect
in every screenshot and does absolutely nothing when a player clicks it.

WHAT THIS CHECKS

A real restart is simulated by stripping every signal connection off the saved
tree, which is precisely what serialising to a file and loading it back does:
instances and attributes survive, connections do not. Then a SECOND, cold copy
of MapPersist — no handlers, no memory of the first — has to bring the map back
to life from the attributes alone.

  1. BAKED IS OBEYED     a flagged map is kept; an unflagged one is not
  2. IT STILL RESPONDS   eggs and gates fire their action after the restart
  3. EDITS SURVIVE       a deleted egg stays deleted, an added part stays added
  4. NO DOUBLE SPAWN     runtime-only folders saved by accident are cleared
  5. NOTHING IS SILENT   an action with no handler is reported, not swallowed
  6. CLICKS ARE LIMITED  map clicks go through a rate limiter like everything
  7. NAMES AGREE         every action the map stamps has a handler in the server
"""
import re
import sys
from pathlib import Path

try:
    import lupa
except ImportError:
    sys.exit("lupa is not installed (pip install lupa)")

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from check_syntax import luau_to_lua  # noqa: E402


def runtime():
    lua = lupa.LuaRuntime(unpack_returned_tuples=False)
    G = lua.globals()
    lua.execute("math.clamp=function(x,l,h) return math.max(l,math.min(h,x)) end;"
                "math.round=function(x) return math.floor(x+0.5) end")
    mock = lua.execute((ROOT / "tools" / "roblox_mock.lua").read_text())
    for k in ("Vector3", "CFrame", "Color3", "Enum", "Instance", "game", "workspace",
              "Random", "UDim", "UDim2", "Vector2"):
        G[k] = mock[k]
    lua.execute("""
        WARNINGS = {}
        task = { spawn=function() end, wait=function() return .03 end,
                 delay=function() end, defer=function() end }
        warn = function(m) WARNINGS[#WARNINGS+1] = tostring(m) end
    """)

    def load(path, name):
        return lua.eval("function(s,n) return assert(load(s,n)) end")(
            luau_to_lua(Path(path).read_text()), "@" + name)()
    return lua, mock, load


def strip_connections(lua, mock):
    """Model saving to a place file and loading it back.

    Parts, their properties and their attributes are written to the file.
    Signal connections are not — they only exist in the memory of the server
    that made them. Clearing them is the whole point: whatever still works
    afterwards works because of what is ON the instances, not because a live
    closure happens to be lying around from the build.
    """
    lua.execute("""
    function STRIP(root)
      local n = 0
      local function walk(inst)
        if rawget(inst, "_sig") then rawset(inst, "_sig", nil); n = n + 1 end
        for _, c in ipairs(rawget(inst, "_c")) do walk(c) end
      end
      walk(root)
      return n
    end
    """)
    return int(lua.globals().STRIP(mock["workspace"]))


def main():
    fails = []
    lua, mock, load = runtime()
    G = lua.globals()
    ws = mock["workspace"]
    G["require"] = mock["robloxRequire"]

    persist1 = load(ROOT / "src/Server/MapPersist.lua", "MapPersist")

    # ---- the first server: build a map the way the builder does ------------
    fired = {"HatchEgg": 0, "BuyArea": 0}
    persist1.Handlers(lua.table_from({
        "HatchEgg": lambda p, a: fired.__setitem__("HatchEgg", fired["HatchEgg"] + 1),
        "BuyArea": lambda p, a: fired.__setitem__("BuyArea", fired["BuyArea"] + 1),
    }))
    root = persist1.Container()
    dets = []
    for i in range(12):
        egg = mock["newInst"]("Part"); egg.Name = "Egg_%d" % i; egg.Parent = root
        cd = mock["newInst"]("ClickDetector"); cd.Parent = egg
        persist1.Bind(cd, "HatchEgg", "Egg%d" % i)
        dets.append(cd)
    for i in range(5):
        gate = mock["newInst"]("Part"); gate.Name = "Barrier_%d" % i; gate.Parent = root
        cd = mock["newInst"]("ClickDetector"); cd.Parent = gate
        persist1.Bind(cd, "BuyArea", "Area%d" % i)
        dets.append(cd)
    print("built map: %d stamped click detectors" % len(dets))

    dets[0].MouseClick["Fire"](dets[0].MouseClick, "player")
    if fired["HatchEgg"] != 1:
        fails.append("a freshly built egg does not respond to a click at all")
    print("  live build: clicking an egg fired its action")

    # ---- the person edits the map and saves the place ---------------------
    doomed = root["FindFirstChild"](root, "Egg_3")
    doomed["Destroy"](doomed)
    mine = mock["newInst"]("Part"); mine.Name = "MyCastleTower"; mine.Parent = root
    orbs = mock["newInst"]("Folder"); orbs.Name = "CoinOrbs"; orbs.Parent = ws
    ghost = mock["newInst"]("Part"); ghost.Name = "CoinOrb"; ghost.Parent = orbs
    root["SetAttribute"](root, "StarPetsBaked", True)

    cleared = strip_connections(lua, mock)
    print("saved place: %d live connections discarded (as a file save does)" % cleared)

    fired["HatchEgg"] = 0
    alive = [d for d in dets if d._p.Parent is not None]
    alive[0].MouseClick["Fire"](alive[0].MouseClick, "player")
    if fired["HatchEgg"] != 0:
        fails.append("the restart simulation is not real — old connections "
                     "survived it, so nothing below proves anything")
    print("  after restart: the old connections are gone (click did nothing)")

    # ---- the second server: cold, and it must not rebuild -----------------
    lua2, mock2, load2 = runtime()
    # Reuse the SAME world: load a fresh MapPersist into the first runtime, so
    # it shares the workspace but has none of the first module's state.
    persist2 = load(ROOT / "src/Server/MapPersist.lua", "MapPersist")

    limited = {"n": 0}

    def allow(player, action):
        limited["n"] += 1
        return limited["n"] <= 3          # a deliberately tight limiter
    persist2.SetRateLimit(lua.table_from({"Allow": allow}))

    got = {"HatchEgg": 0, "BuyArea": 0}
    persist2.Handlers(lua.table_from({
        "HatchEgg": lambda p, a: got.__setitem__("HatchEgg", got["HatchEgg"] + 1),
        "BuyArea": lambda p, a: got.__setitem__("BuyArea", got["BuyArea"] + 1),
    }))

    if not persist2.Boot():
        fails.append("a map flagged StarPetsBaked was NOT recognised — the "
                     "server would rebuild over it and destroy the build again")
    else:
        print("  baked flag honoured: the map is kept, not regenerated")

    rewired = int(persist2.Rewire())
    print("  rewired %d interactive parts from attributes alone" % rewired)
    if rewired != len(dets) - 1:      # one egg was deleted by hand
        fails.append("rewired %d of %d stamped parts — the rest are scenery"
                     % (rewired, len(dets) - 1))

    # 2. IT STILL RESPONDS
    gate = next(d for d in dets
                if d._p.Parent is not None
                and str(d["GetAttribute"](d, "SPAction")) == "BuyArea")
    gate.MouseClick["Fire"](gate.MouseClick, "player")
    if got["BuyArea"] != 1:
        fails.append("a buy-gate in a baked map does nothing when clicked — "
                     "worlds cannot be bought")
    else:
        print("  a buy-gate fires its action with no builder involved")

    # 3. EDITS SURVIVE
    if root["FindFirstChild"](root, "MyCastleTower") is None:
        fails.append("a hand-built part inside the baked map was destroyed")
    else:
        print("  a hand-built part inside the map survived untouched")
    if root["FindFirstChild"](root, "Egg_3") is not None:
        fails.append("an egg the person deleted came back — the map WAS rebuilt")
    else:
        print("  an egg deleted by hand stayed deleted")

    # 4. NO DOUBLE SPAWN
    if ws["FindFirstChild"](ws, "CoinOrbs") is not None:
        fails.append("a CoinOrbs folder saved into the place was kept, so every "
                     "coin spawns twice in the same spot")
    else:
        print("  runtime-only folders saved by accident were cleared")

    # 5. NOTHING IS SILENT
    lua.execute("WARNINGS = {}")
    lone = mock["newInst"]("ClickDetector")
    lone["SetAttribute"](lone, "SPAction", "SomethingTheCodeDoesNotKnow")
    lone.Parent = root
    persist2.Rewire()
    lone.MouseClick["Fire"](lone.MouseClick, "player")
    warns = [str(w) for w in G.WARNINGS.values()]
    if not any("SomethingTheCodeDoesNotKnow" in w for w in warns):
        fails.append("a part asking for an action the code does not define was "
                     "ignored in silence")
    else:
        print("  an unknown map action is reported by name, not swallowed")
    stamped, live, unknown = persist2.Audit()
    if "SomethingTheCodeDoesNotKnow" not in {str(k) for k in dict(unknown).keys()}:
        fails.append("Audit() does not report the unknown action")
    else:
        print("  the audit reports it too (%d stamped, %d live)" % (stamped, live))

    # 6. CLICKS ARE LIMITED
    # ClickDetectors never pass through any guard around the remotes: the client
    # does not send a remote, Roblox fires MouseClick on the server directly. An
    # exploiter can drive that as fast as they like, and one of these handlers
    # writes to player data.
    before = got["BuyArea"]
    for _ in range(20):
        gate.MouseClick["Fire"](gate.MouseClick, "player")
    passed = got["BuyArea"] - before
    if passed >= 20:
        fails.append("20 rapid map clicks all reached the handler — map "
                     "interaction bypasses the rate limiter entirely")
    else:
        print("  20 rapid clicks, %d reached the handler (limiter applies)" % passed)

    # 7. NAMES AGREE — static, across the real server file
    server = (ROOT / "src/Server/GameServer.server.lua").read_text()
    block = re.search(r"MapPersist\.Handlers\(\{(.*?)\n\}\)", server, re.S)
    handled = set(re.findall(r"^\t(\w+) = function", block.group(1), re.M)) if block else set()
    stamped_names = set()
    for f in (ROOT / "src/Server").glob("*.lua"):
        stamped_names |= set(re.findall(
            r'MapPersist\.Bind\(\s*\w+,\s*"(\w+)"', f.read_text()))
    stamped_names |= set(re.findall(
        r'MapPersist\.Bind\(\s*\w+,\s*"(\w+)"', server))
    missing = stamped_names - handled
    if missing:
        fails.append("the map stamps %s but the server defines no handler for "
                     "it — those parts are scenery" % ", ".join(sorted(missing)))
    else:
        print("  all %d stamped actions have a handler: %s"
              % (len(stamped_names), ", ".join(sorted(stamped_names))))

    if fails:
        print("\nbake: %d problems" % len(fails))
        for f in fails:
            print("   x " + f)
        return 1
    print("\nbake: a map saved into the place keeps every edit AND still works")
    return 0


if __name__ == "__main__":
    sys.exit(main())
